export interface BlogPost {
  slug: string;
  title: string;
  excerpt: string;
  content: string;
  author: string;
  authorRole: string;
  date: string;
  readTime: string;
  category: 'Scriptwriting' | 'Retention & Growth' | 'AI & Workflow' | 'YouTube Strategy';
  tags: string[];
}

export const blogPosts: BlogPost[] = [
  {
    slug: '3-second-hook-formula-youtube-shorts',
    title: 'The 3-Second Hook Formula for YouTube Shorts & TikTok',
    excerpt: 'How top creators stop the scroll in under 3 seconds using contrarian curiosity and emotional stakes.',
    category: 'YouTube Strategy',
    author: 'Jayant',
    authorRole: 'Founder & Creator',
    date: 'Aug 16, 2026',
    readTime: '4 min read',
    tags: ['Hooks', 'Shorts', 'TikTok', 'Retention'],
    content: `
### Why Most Hooks Fail
On short-form video platforms, over 70% of swiped-away viewers leave within the first 2.5 seconds. If your opening sentence is "Hey guys, welcome back to my channel," your video is statistically dead on arrival.

Great hooks don't introduce who you are. They introduce an immediate tension or unsolved curiosity loop.

---

### The 3 Essential Hook Types

#### 1. The Contrarian Myth-Buster
State a widely believed concept, then immediately state why it is completely wrong.
- *Example*: "Everyone tells you to post 3 times a day on TikTok. That is the exact reason your views are stuck at 200."

#### 2. The High-Stakes Story Opener
Drop the viewer directly into the climax of a story without preamble.
- *Example*: "I lost $4,000 in 10 minutes because I made one rookie camera mistake."

#### 3. The Specific Curiosity Gap
Promise a tangible, unusual outcome with high specificity.
- *Example*: "This 4-word tweak increased my video retention from 35% to 78%."

---

### How to Apply This in ScriptFlow
When drafting your scripts in ScriptFlow:
1. Open the **Hook Library** on the right panel.
2. Select **Contrarian** or **Curiosity** categories.
3. Test 3 different hook variations before you write the body of your script.
    `
  },
  {
    slug: 'structure-10-minute-video-high-retention',
    title: 'How to Structure a 10-Minute Video for 60%+ Audience Retention',
    excerpt: 'A step-by-step masterclass on pacing, micro-payoffs, and B-roll cue planning to keep long-form viewers hooked.',
    category: 'Retention & Growth',
    author: 'ScriptFlow Editorial',
    authorRole: 'Video Production Team',
    date: 'Aug 14, 2026',
    readTime: '6 min read',
    tags: ['Long Form', 'Pacing', 'Storytelling'],
    content: `
### The Retention Problem in Long-Form Video
Long-form YouTube videos don't fail in the middle because the topic is boring. They fail because the script delivers monotone pacing without **micro-payoffs**.

A micro-payoff is an insight, visual change, or comedic beat delivered every 45 to 60 seconds that rewards the viewer for staying.

---

### The 4-Part Long-Form Architecture

\`\`\`
Hook (0:00 - 0:30) ➔ Problem Agitation (0:30 - 2:00) ➔ Core Framework (2:00 - 8:30) ➔ Climax & Next Action (8:30 - 10:00)
\`\`\`

#### 1. The Setup (0:00 - 0:30)
Establish what the video is about and deliver the initial proof that you know what you are talking about.

#### 2. The Obstacle (0:30 - 2:00)
Why does standard advice fail? Why is the viewer struggling with this topic today?

#### 3. The 3 Core Pillars with Visual Cues (2:00 - 8:30)
Break your solution into 3 distinct steps. Use ScriptFlow's **B-Roll & Production Planner** to alternate between talking head and visual screen recordings.

#### 4. The Bridge CTA (8:30 - 10:00)
Never say "In conclusion" or "That's all for today" — viewer drop-off spikes by 80% on transition phrases. Instead, bridge seamlessly into your recommended next video.
    `
  },
  {
    slug: 'ai-scriptwriting-without-losing-your-voice',
    title: 'How to Use AI for Scriptwriting Without Losing Your Authentic Voice',
    excerpt: 'Why generic ChatGPT scripts sound robotic, and how non-destructive AI text improvements elevate your raw personality.',
    category: 'AI & Workflow',
    author: 'Jayant',
    authorRole: 'Founder',
    date: 'Aug 10, 2026',
    readTime: '5 min read',
    tags: ['AI Writing', 'Gemini', 'Creator Tone'],
    content: `
### The "AI Slop" Epidemic
We have all seen YouTube videos that sound like they were generated by an eager corporate robot. They use phrases like "In today's fast-paced digital landscape" or "Let's dive deep into this fascinating topic."

Viewers have developed an instinctual radar for AI generated phrasing.

---

### The Rule of Human-First Scripting
At ScriptFlow, our fundamental design rule is **"Write your way. Improve it with AI."**

1. **You write the raw draft**: Capture your unique slang, cadence, stories, and opinions.
2. **AI handles surgery, not writing**: Use AI for surgical tweaks:
   - *Shortening* long-winded run-on sentences
   - *Clarity* without changing meaning
   - *Punchier hooks* based on your actual words
   - *Repurposing* your finished master script into Twitter threads or Shorts.

By keeping human creativity at the core, your scripts stay 100% authentic while taking 70% less editing time.
    `
  }
];
